- name: Deploy new container
env:
  DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
  GOOGLE_REDIRECT_URI: ${{ secrets.GOOGLE_REDIRECT_URI }}
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_PORT: ${{ secrets.DB_PORT }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
run: |
  ssh -o StrictHostKeyChecking=no root@51.210.102.229 << EOF
    echo "Deploying new container..."
    docker run -d -p 80:80 --name zenplanner \
      -e DJANGO_SECRET_KEY='$DJANGO_SECRET_KEY' \
      -e GOOGLE_CLIENT_ID='$GOOGLE_CLIENT_ID' \
      -e GOOGLE_CLIENT_SECRET='$GOOGLE_CLIENT_SECRET' \
      -e GOOGLE_REDIRECT_URI='$GOOGLE_REDIRECT_URI' \
      -e DB_HOST='$DB_HOST' \
      -e DB_PORT='$DB_PORT' \
      -e DB_USER='$DB_USER' \
      -e DB_PASSWORD='$DB_PASSWORD' \
      ghcr.io/${{ github.repository }}/my-image:latest
    echo "Running migrations..."
    docker exec zenplanner /wait-for-it.sh ${DB_HOST}:${DB_PORT} --strict --timeout=300 -- /app/venv/bin/python manage.py migrate
    docker exec zenplanner /app/venv/bin/python manage.py collectstatic --noinput
  EOF
